openapi: 3.0.0
info:
  title: CloseWorkItem API
  version: 'v1'
servers:
  - url: https://dev.api.communityfibre.co.uk/dev/work-item/v1
         
  
paths:
  /0.0/close:
     description: To close work items in HOBS
     post:
      description: To close work items in HOBS
      tags:
      - CloseWorkItem
      security:
        - bearerAuth: []

      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - itemID
                - requestType
                - remarks
              properties:
                itemID: 
                  type: string
                  example: 'C-1320702666'
                requestType:
                  type: string
                  example: 'CLOSE_WORKITEM'
                remarks:
                  type: string
                  example: 'the item is closed immediately'
            example:
              itemID: 'C-1320702666'
              requestType: 'CLOSE_WORKITEM'
              remarks: 'the item is closed immediately'
              
              
      responses:
        200:
          description: work item closed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  interactionID:
                    type: string
                    example: 'CWI-1699935962664'
                  opID:
                    type: string
                    example: 'CFL'
                  buID:
                    type: string
                    example: 'DEFAULT'
                  statusList:
                    type: array
                    items:
                      type: object
                      properties:
                        statusCode:
                          type: string
                          example: '0000'
                        statusType:
                          type: string
                          example: 'Informational'
                        statusName:
                          type: string
                          example: 'Informational'
                        statusDescription:
                          type: string
                          example: 'SUCCESS'
              example:
                interactionID: 'CWI-1699935962664'
                opID: 'CFL'
                buID: 'DEFAULT'
                statusList: 
                  - statusCode: '0000'
                    statusType: 'Informational'
                    statusName: 'Informational'
                    statusDescription: 'SUCCESS'
                  
                  
        400:                        
          description: MALFORMED_REQUEST
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    example: "2b7e6837-0ec3-4ee9-acba-8250768c5ef9"
                  code:
                    type: string
                    example: "MALFORMED_REQUEST"
                  messages:
                    type: array
                    items:
                      type: string
                      example: "Problem parsing request parameters - missing mandatory parameter(s)"
              example:
                uuid: "2b7e6837-0ec3-4ee9-acba-8250768c5ef9"
                code: "MALFORMED_REQUEST"
                messages:
                    - "Problem parsing request parameters - missing mandatory parameter(s)"


        401:  
          description: NOT_AUTHORISED
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    example: "1e7e7ebc-c797-4d60-a81c-940b40631957"
                  code:
                    type: string
                    example: "NOT_AUTHORISED"
                  messages:
                    type: array
                    items:
                      type: string
                      example: "Not authorised to use this endpoint"
              example:
                uuid: "1e7e7ebc-c797-4d60-a81c-940b40631957"
                code: "NOT_AUTHORISED"
                messages:
                    - "Not authorised to use this endpoint"


        500:  
          description: SUPPLIER_FAULT
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    example: "43c871f3-18f4-46f8-9674-26ccd1dcee14"
                  code:
                    type: string
                    example: "SUPPLIER_FAULT"
                  messages:
                    type: array
                    items:
                      type: string
                      example: "An unexpected system error occurred"
              example:
                uuid: "43c871f3-18f4-46f8-9674-26ccd1dcee14"
                code: "SUPPLIER_FAULT"
                messages:
                    - "An unexpected system error occurred"     
         
components:
  securitySchemes:
    bearerAuth:
      description: |
        The Apigee Gateway can support a number of different authentication mechanisms e.g. JWT bearer tokens
      type: http
      scheme: bearer
      bearerFormat: JWT     
