openapi: 3.0.0
info:
  title: CreateWorkItem API
  version: 'v1'
servers:
  - url: https://dev.api.communityfibre.co.uk/dev/work-item/v1
paths:
  /0.0/create:
    description: Endpoint to create a work item in HOBS CRM
    post:
      tags:
      - WorkItem
      security:
        - bearerAuth: []

      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - reason
              properties:
                reason:
                  type: string
                  example: "Billing or Contract Query"
                  enum:
                    - No Internet Connection
                    - Billing or Contract Query
                    - Technical Issue
                    - Appointment Query
                    - Business Query
                    - Voice or TV Products
                    - Upgrade or Renewals
                    - Moving Home
                    - Freeze Contract
                    - Account Transfer or Bereavement
                    - Change or Add Contact Details
                    - My account
                    - Referrals or Vouchers
                    - Complaint
                    - Cancellation Request
                    - Marketing Preferences
                    - Issue Not Listed
                    - RPA request
                    - IVR request
                    - Networks_Provisioning_issues
                    - Engineering_inaccessible_drop_mdu
                    - Engineering_inaccessible_drop_SDU_UG
                    - Engineering_inaccessible_drop_SDU_OH
                    - Technical_network adjustments
                    - Engineering_drop_feasibility
                    - Engineering_Other
                    - Technical Inaccessible drop
                    - Technical_Low_Power
                    - Technical_missing_drop
                    - Technical_No_Power
                    - Technical_Splitter_DP
                    - Technical_Damaged_Drop
                    - Customer_Inaccesible_Drop
                    - Customer_No_Answer
                    - Customer_Rejected_Work
                    - Customer_Counter_Offer
                    - Customer_Long_term_contract
                    - Customer_Cancelled
                    - Customer_rescheduled
                    - customer_not_interested
                    - customer_no_direct_debit
                    - customer_other
                    - CPE Returns
                subreason:
                  type: string
                  nullable: true
                  example: "Installation"
                  enum:
                    - 
                    - Installation
                    - Provide feedback on staff
                    - About My Contract
                    - Free Add on Promised
                    - 60 Days Satisfaction Guarantee
                    - Broadband service
                    - TV & Voice
                    - Trust Pilot
                    - Billing
                    - Technical Reason
                    - Billing Reason
                    - Moving to another provider
                    - Unhappy with contract
                    - Financial hardship
                    - Unhappy with recent appointment
                description:
                  type: string
                  example: "customer is reporting a problem"
                customerId:
                  type: string
                  example: "C20100651"
                accountId:
                  type: string
                  example: "AD17813"
                subscriberId:
                  type: string
                  example: "S1255921"
                itemContactInfo:
                  type: object
                  properties:
                    formofaddress:
                      type: string
                      example: "Mr"
                    firstName:
                      type: string
                      example: "sravan kumar"
                    lastName:
                      type: string
                      example: "ask"
                    addressLine1:
                      type: string
                      example: "FLAT 2 ADA HOUSE ADA PLACE"
                    addressLine2:
                      type: string
                      example: "Tower Hamlets"
                    addressLine3:
                      type: string
                      example: ""
                    city:
                      type: string
                      example: "LONDON"
                    state:
                      type: string
                      example: "Tower Hamlets"
                    country:
                      type: string
                      example: "ENG"
                    zipcode:
                      type: string
                      example: "E2 9BB"
                    emailID:
                      type: string
                      example: "Sravan@tcs.com"
                    mobileNumber:
                      type: string
                      example: "6677556655"
            example:
              reason: "Billing Query"
              subreason: "Installation"
              description: "customer is reporting a problem"
              customerId: "C20100651"
              accountId: "AD17813"
              subscriberId: "S1255921"
              itemContactInfo: 
                formofaddress: "Mr"
                firstName: "sravan kumar"
                lastName: "ask"
                addressLine1: "FLAT 2 ADA HOUSE ADA PLACE"
                addressLine2: "Tower Hamlets"
                addressLine3: ""
                city: "LONDON"
                state: "Tower Hamlets"
                country: "ENG"
                zipcode: "E2 9BB"
                emailID: "Sravan@tcs.com"
                mobileNumber: "6677556655"

      responses:
        200:
          description: Endpoint to create a work item in HOBS CRM
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/CustomerID'
                  - $ref: '#/components/schemas/ContactInfo'

              examples:
                CustomerID: 
                  value:
                    buId: "DEFAULT"
                    itemId: "C-1320713692"
                    accountId: "AD17813"
                    statusList: 
                    - statusCode: "0000"
                      statusDescription: "SUCCESS"
                      statusType: "Informational"
                    opId: "CFL"
                    customerId: "C20100651"
                    action: "CREATEWORKITEM"
                    description: "customer is reporting broadband issues"
                    typeId: "COMP-BRDBAND"
                    subTypeId: "COMP-BRDBAND-OTHER"
                    userId: "CFLHOBS"
                    categoryId: "COMP"

                ContactInfo:
                  value:
                    buId: "DEFAULT"
                    itemId: "C-1320735627"
                    statusList: 
                    - statusCode: "0000"
                      statusDescription: "SUCCESS"
                      statusType: "Informational"
                    opId: "CFL"
                    action: "CREATEWORKITEM"
                    description: "customer is reporting a problem"
                    typeId: "COMP-BRDBAND"
                    subTypeId: "COMP-BRDBAND-OTHER"
                    itemContactInfo: 
                      formofaddress: "Mr"
                      firstName: "sravan kumar"
                      lastName: "ask"
                      addressLine1: "FLAT 2 ADA HOUSE ADA PLACE"
                      addressLine2: "Tower Hamlets"
                      addressLine3: ""
                      city: "LONDON"
                      state: "Tower Hamlets"
                      country: "ENG"
                      zipcode: "E2 9BB"
                      emailID: "Sravan@tcs.com"
                      mobileNumber: "6677556655"
 
        '400':                        
          description: MALFORMED_REQUEST
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    example: "2b7e6837-0ec3-4ee9-acba-8250768c5ef9"
                  code:
                    type: string
                    example: "MALFORMED_REQUEST"
                  messages:
                    type: array
                    items:
                      type: string
                      example: "Problem parsing request parameters - missing mandatory parameter(s)"
              example:
                uuid: "2b7e6837-0ec3-4ee9-acba-8250768c5ef9"
                code: "MALFORMED_REQUEST"
                messages:
                    - "Problem parsing request parameters - missing mandatory parameter(s)"

        '401':  
          description: NOT_AUTHORISED
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    example: "1e7e7ebc-c797-4d60-a81c-940b40631957"
                  code:
                    type: string
                    example: "NOT_AUTHORISED"
                  messages:
                    type: array
                    items:
                      type: string
                      example: "Not authorised to use this endpoint"
              example:
                uuid: "1e7e7ebc-c797-4d60-a81c-940b40631957"
                code: "NOT_AUTHORISED"
                messages:
                    - "Not authorised to use this endpoint"

        '500':  
          description: SUPPLIER_FAULT
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    example: "43c871f3-18f4-46f8-9674-26ccd1dcee14"
                  code:
                    type: string
                    example: "SUPPLIER_FAULT"
                  messages:
                    type: array
                    items:
                      type: string
                      example: "An unexpected system error occurred"
              example:
                uuid: "43c871f3-18f4-46f8-9674-26ccd1dcee14"
                code: "SUPPLIER_FAULT"
                messages:
                    - "An unexpected system error occurred"     


components:
  securitySchemes:
    bearerAuth:
      description: |
        The Apigee Gateway can support a number of different authentication mechanisms e.g. JWT bearer tokens
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
      CustomerID:
        type: object
        properties:
          buId:
            type: string
            example: "DEFAULT"
          itemId:
            type: string
            example: "C-1320713692"
          accountId:
            type: string
            example: "AD17813"
          statusList:
            type: array
            items:
              type: object
              properties:
                statusCode:
                  type: string
                  example: "0000"
                statusDescription:
                  type: string
                  example: "SUCCESS"
                statusType:
                  type: string
                  example: "Informational"
          opId:
            type: string
            example: "CFL"
          customerId:
            type: string
            example: "C20100651"
          action:
            type: string
            example: "CREATEWORKITEM"
          description:
            type: string
            example: "customer is reporting broadband issues"
          typeId:
            type: string
            example: "COMP-BRDBAND"
          subTypeId:
            type: string
            example: "COMP-BRDBAND-OTHER"
          userId:
            type: string
            example: "CFLHOBS"
          categoryId:
            type: string
            example: "COMP"

      ContactInfo:  
        type: object
        properties:
          buId:
            type: string
            example: "DEFAULT"
          itemId:
            type: string
            example: "C-1320735627"
          statusList:
            type: array
            items:
              type: object
              properties:
                statusCode:
                  type: string
                  example: "0000"
                statusDescription:
                  type: string
                  example: "SUCCESS"
                statusType:
                  type: string
                  example: "Informational"
          opId:
            type: string
            example: "CFL"
          action:
            type: string
            example: "CREATEWORKITEM"
          description:
            type: string
            example: "customer is reporting a problem"
          typeId:
            type: string
            example: "COMP-BRDBAND"
          subTypeId:
            type: string
            example: "COMP-BRDBAND-OTHER"
          itemContactInfo:
            type: object
            properties:
              formofaddress:
                type: string
                example: "Mr"
              firstName:
                type: string
                example: "sravan kumar"
              lastName:
                type: string
                example: "ask"
              addressLine1:
                type: string
                example: "FLAT 2 ADA HOUSE ADA PLACE"
              addressLine2:
                type: string
                example: "Tower Hamlets"
              addressLine3:
                type: string
                example: ""
              city:
                type: string
                example: "LONDON"
              state:
                type: string
                example: "Tower Hamlets"
              country:
                type: string
                example: "ENG"
              zipcode:
                type: string
                example: "E2 9BB"
              emailID:
                type: string
                example: "Sravan@tcs.com"
              mobileNumber:
                type: string
                example: "6677556655"
